subscription_id = "<your-subscription-id>"
client_id       = "<your-client-id>"
client_secret   = "<your-client-secret>"
tenant_id       = "<your-tenant-id>"
resource_group_name = "example-rg"
location        = "East US"
