environment                = "dev"
resource_group_location    = "eastus"
product_name               = "devsecops"
app_name                   = "mydevtestapp"  azure_region = "eastus"
  environment_name = "prod"
